# Generated by Django 6.0.1 on 2026-01-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('preferred_skills', models.JSONField(blank=True, default=list, help_text='List of preferred skills')),
                ('experience_years', models.IntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='AI extraction keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
