# Generated by Django 6.0.1 on 2026-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequirement',
            name='compliance_requirements',
            field=models.JSONField(blank=True, default=list, help_text='Regulatory or compliance requirements'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='file',
            field=models.FileField(blank=True, help_text='Original JD file', null=True, upload_to='jds/'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='industry_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Save as reusable template'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='mandatory_certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of mandatory certifications'),
        ),
    ]
