# Generated by Django 6.0.1 on 2026-01-08 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('parsed_content', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(help_text='Overall match score (0-100)')),
                ('skill_match_score', models.FloatField(default=0.0)),
                ('missing_skills', models.JSONField(default=list)),
                ('matched_skills', models.JSONField(default=list)),
                ('ai_explanation', models.TextField(blank=True, help_text='AI generated explanation')),
                ('classification', models.CharField(choices=[('SHORTLISTED', 'Shortlisted'), ('MAYBE', 'Maybe'), ('REJECTED', 'Rejected')], default='MAYBE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='jobs.jobrequirement')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='resumes.resume')),
            ],
            options={
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
