# Generated by Django 6.0.1 on 2026-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_candidateprofile_profileversion_submissionactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='semantic_score',
            field=models.FloatField(default=0.0, help_text='Semantic similarity score (0-100)'),
        ),
    ]
