# Generated by Django 6.0.1 on 2026-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_add_jd_title_to_scanrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresult',
            name='document_quality_label',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='document_quality_score',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='improvement_suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='jd_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='resume_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
